(defun find-num ()
  (skip-chars-forward "^0-9")
  (let ((beg (point))
        (end (progn (skip-chars-forward "0-9.") (point))))
    (if (char-equal (following-char) ?h) (string-to-number (buffer-substring beg end)) 0)))

(defun sum-hours ()
  (interactive)
  (setq sum 0)
  (let ( (end (max (point) (mark)))
         (beg (min (point) (mark))))
    (goto-char beg)
    (while (< (point) end)
      (let ((new (find-num)))
        (if (< (point) end)
            (setq sum (+ sum new))
          ())))
    (goto-char end)
    (insert "\n")
    (insert (number-to-string sum))))
