#!/bin/bash

if [[ $# == 0 ]]
then
  echo "Give at least one param understood by gawk"
  exit 1
fi

if [[ $# == 1 ]]
then
  gawk "{ print \$$1; }"
elif [[ $# == 2 ]]
then
  gawk "{ print \$$1, \$$2; }"
elif [[ $# == 3 ]]
then
  gawk "{ print \$$1, \$$2, \$$3; }"
fi
